### ISSUE TITLE
babel-loader presets

### ISSUE THREAD

**Issue by kbetts** [shamahoque/mern-simplesetup#1]
I ran into an issue with the webpack build failing. It can be fixed by setting the "presets" option for `babel-loader` to `react` in the webpack.config.js file. 

The issue is probably a nuance to my environment, although there is some background [here](https://webpack.js.org/loaders/babel-loader/) and [here](https://webpack.js.org/configuration/module/#rule-options-rule-query). The preferred solution is to probably use a .babelrc config file as described [here](https://www.npmjs.com/package/babel-preset-react).

Original webpack.config.js file,

<img width="497" alt="webpack_config_client_js_orig" src="https://user-images.githubusercontent.com/4656145/43940443-7f70f768-9c24-11e8-9638-98efe30ae60a.png">

Adding a "preset" option for `babel-loader` in the `module.rules` array solves the issue (although see the link above regarding the .babelrc config file solution),

<img width="361" alt="webpack_config_client_js_fix" src="https://user-images.githubusercontent.com/4656145/43940452-8b2e9c18-9c24-11e8-945b-0325fe68389c.png">

**Comment by shamahoque** [comment]
The code actually does have a [.babelrc](https://github.com/shamahoque/mern-simplesetup/blob/master/.babelrc) config file, as discussed in the book under Chapter 2: Preparing the Development Environment -> Checking your development setup -> Configuring Babel, Webpack, and Nodemon.

But I just saw that the .babelrc file is missing in the PacktPublishing/Full-Stack-React-Projects code repository. Thank you for pointing this out.

**Comment by kbetts** [comment]
Thank you for following up so quickly. I had cloned the Packt repository. Build works perfectly after reverting the webpack.config.js file and added the .babelrc found here.
