### ISSUE TITLE
[nodemon] app crashed - TypeError: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by najdi123** [shamahoque/mern-simplesetup#3]
I did everything that the book said. There were a few obvious mistakes like the book said "Create a nodemon.js file in your project folder", I've been trying to find the differences between what I had and the code here and I can't remember the other couple of them, but I am sure they existed.
Also the readme says I need MongoDB (3.6.3) which is not out yet, apparently this is written in future. Also in comparing my code with this repository I found this in package.json "engines": { "node": "8.11.1", "npm": "5.8.0"  },"  which was not mentioned in the book.
 I think I compared everything but my code wont run but fortunately this repository does work.
I wish I could make my own code work. Is there any document that would tell me what I need to change to make it work?

I didn't write this, how could have I made a mistake there?
C:\29\mern-simplesetup\node_modules\webpack-cli\bin\config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined

**Comment by shamahoque** [comment]
This seems like a npm module version issue. You can start by comparing the package version numbers in the package.json from this repository with your package.json. Modify any version discrepancies, remove the node-modules folder and npm install again. 

The engines declaration in package.json won't effect your code if you have the correct Node and npm versions already installed.

MongoDB current version is 4.0, 3.6.3 was released in Feb 18: 
[https://docs.mongodb.com/manual/release-notes/3.6/](https://docs.mongodb.com/manual/release-notes/3.6/)

For any errata in the book, refer to this page, and also feel free to report any issues you find:
[https://www.packtpub.com/books/content/support/33541](https://www.packtpub.com/books/content/support/33541)

**Comment by RashedKhalfan** [comment]
I solved this problem for this book as the following 

1- installed MongoDB using brew 
2- keep separate terminal with command `mongod` running
3- `npm run development`

**Comment by carloscastellanos** [comment]
> This seems like a npm module version issue. You can start by comparing the package version numbers in the package.json from this repository with your package.json. Modify any version discrepancies, remove the node-modules folder and npm install again.
> 
> The engines declaration in package.json won't effect your code if you have the correct Node and npm versions already installed.
> 
> MongoDB current version is 4.0, 3.6.3 was released in Feb 18:
> https://docs.mongodb.com/manual/release-notes/3.6/
> 
> For any errata in the book, refer to this page, and also feel free to report any issues you find:
> https://www.packtpub.com/books/content/support/33541

This works. More detailed info on setting up the package.json file would've been useful however.
