### ISSUE TITLE
.babel.rc missing a comma

### ISSUE THREAD

**Issue by carloscastellanos** [shamahoque/mern-simplesetup#4]
The electronic version of the book is missing a comma on the .babelrc (right after "stage-2"). Don't know about the print version.

<img width="1777" alt="babel" src="https://user-images.githubusercontent.com/6315240/56336284-61170300-6165-11e9-9cc8-5534154259f2.png">

**Comment by shamahoque** [comment]
Thank you for pointing this out. An errata has been submitted with Packt in this regard.
