### ISSUE TITLE
"nodeExternals is not defined"

### ISSUE THREAD

**Issue by rrdirnens** [shamahoque/mern-simplesetup#7]
![image](https://user-images.githubusercontent.com/42729985/69877102-eb157580-12c9-11ea-90e0-bf045af7ccfc.png)
![image](https://user-images.githubusercontent.com/42729985/69877121-f2d51a00-12c9-11ea-85e0-072fe1463192.png)

Not sure what the problem is. Checked the error online, but couldn't find anyone who's encountered the same err.

**Comment by rrdirnens** [comment]
I reverted the package.json versions to exactly the ones in the book and source code, but after deleting modules, running npm install and npm run development, it gives me the same error. I did this a couple of times and once it gave me a different err:  
![image](https://user-images.githubusercontent.com/42729985/69878070-86a7e580-12cc-11ea-8d9d-195b8f6a806a.png)

So I looked online for help and found that I should update webpack and webpack-cli to newer versions, so I did and got the nodeExternals err again. So I'm stuck there atm, but can't seem to reproduce the err in the last pic anymore. Greatly appreciate any help.

**Comment by Jahchap** [comment]
In the webpack.config.server.js file, weback externals calls nodeExternals() that doesn't seem defined anywhere. So replace that with regex. See code below.

`const path = require('path')
const webpack = require('webpack')
const CURRENT_WORKING_DIR = process.cwd()

const config = {
    name: "server",
entry: [ path.join(CURRENT_WORKING_DIR , './server/server.js') ],
    target: "node",
    output: {
        path: path.join(CURRENT_WORKING_DIR , '/dist/'),
        filename: "server.generated.js",
        publicPath: '/dist/',
        libraryTarget: "commonjs2"
    },
    externals: [/^[a-z\-0-9]+$/],
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: [ 'babel-loader' ]
            }
        ]
    }
}

module.exports = config`

Cheers!

**Comment by Jahchap** [comment]
In the **webpack.config.server.js** file, weback externals calls **nodeExternals()** that doesn't seem defined anywhere. So replace that with **regex**. See code working below.

```
const path = require('path')
const webpack = require('webpack')
const CURRENT_WORKING_DIR = process.cwd()

const config = {
    name: "server",
entry: [ path.join(CURRENT_WORKING_DIR , './server/server.js') ],
    target: "node",
    output: {
        path: path.join(CURRENT_WORKING_DIR , '/dist/'),
        filename: "server.generated.js",
        publicPath: '/dist/',
        libraryTarget: "commonjs2"
    },
    externals: [/^[a-z\-0-9]+$/],
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: [ 'babel-loader' ]
            }
        ]
    }
}
```

Cheers!

**Comment by Jahchap** [comment]
In the **webpack.config.server.js** file, weback externals calls **nodeExternals()** that doesn't seem defined anywhere. So replace that with **regex**. See working code below.

```
const path = require('path')
const webpack = require('webpack')
const CURRENT_WORKING_DIR = process.cwd()

const config = {
    name: "server",
entry: [ path.join(CURRENT_WORKING_DIR , './server/server.js') ],
    target: "node",
    output: {
        path: path.join(CURRENT_WORKING_DIR , '/dist/'),
        filename: "server.generated.js",
        publicPath: '/dist/',
        libraryTarget: "commonjs2"
    },
    externals: [/^[a-z\-0-9]+$/],
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: [ 'babel-loader' ]
            }
        ]
    }
}
```

Cheers!

**Comment by NickSasseen** [comment]
> In the **webpack.config.server.js** file, weback externals calls **nodeExternals()** that doesn't seem defined anywhere. So replace that with **regex**. See working code below.
> 
> ```
> const path = require('path')
> const webpack = require('webpack')
> const CURRENT_WORKING_DIR = process.cwd()
> 
> const config = {
>     name: "server",
> entry: [ path.join(CURRENT_WORKING_DIR , './server/server.js') ],
>     target: "node",
>     output: {
>         path: path.join(CURRENT_WORKING_DIR , '/dist/'),
>         filename: "server.generated.js",
>         publicPath: '/dist/',
>         libraryTarget: "commonjs2"
>     },
>     externals: [/^[a-z\-0-9]+$/],
>     module: {
>         rules: [
>             {
>                 test: /\.js$/,
>                 exclude: /node_modules/,
>                 use: [ 'babel-loader' ]
>             }
>         ]
>     }
> }
> ```
> 
> Cheers!

Ran into this same road block. This helped. Thanks!
